-- Council Training: the curriculum, and a clean slate (2026-10-06).
--
-- 1. The sweep. Modules built before the curriculum existed are removed,
--    with their drafts, versions and everyone's progress, along with the
--    AI builds that made them and any completions earned against them.
--    Only things created before the curriculum was first seeded are
--    removed, so running this again never touches later work.
-- 2. The curriculum map: 17 modules as unpublished shells (title, scope,
--    minutes, learning objectives and further reading), ready to build.
--    Learners see them as "Coming soon" until each is published.
-- 3. AI builds can target one curriculum module (training_imports.module_id).
--
-- Safe to re-run.

alter table public.training_modules
  add column if not exists curriculum_key text;
create unique index if not exists training_modules_curriculum_key_idx
  on public.training_modules (curriculum_key) where curriculum_key is not null;

alter table public.training_imports
  add column if not exists module_id uuid references public.training_modules(id) on delete set null;

-- ── 1. The sweep ───────────────────────────────────────────────────────
do $$
declare
  v_seeded timestamptz := coalesce(
    (select min(created_at) from public.training_modules where curriculum_key is not null),
    now()
  );
begin
  delete from public.training_modules where curriculum_key is null and created_at < v_seeded;
  delete from public.training_imports where created_at < v_seeded;
  delete from public.training_credentials where issued_at < v_seeded;
end $$;

-- ── 2. The curriculum ──────────────────────────────────────────────────
with seed (curriculum_key, track_code, order_index, title, summary, estimated_minutes, content) as (
  values
  ('sb1', 'strata_basics', 1, 'What a strata is', 'Strata lots, common property and unit entitlement, and the documents that govern a strata.', 12, '{"objectives": ["Explain the difference between a strata lot, common property and limited common property", "Describe what unit entitlement decides for each owner", "Name the documents that govern a strata and which one wins when they disagree", "Explain that the strata corporation is all the owners together, acting as one legal body"], "sections": [], "furtherReading": [{"id": "fr_sb1_1", "title": "Living in a strata (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/understanding-stratas/living-in-a-strata", "note": "A plain-language introduction for owners."}, {"id": "fr_sb1_2", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}, {"id": "fr_sb1_3", "title": "Strata housing: find it fast (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/find-it-fast", "note": "Every topic in the Province''s strata guide, on one page."}]}'::jsonb),
  ('sb2', 'strata_basics', 2, 'Who decides what', 'Owners, council, the strata manager and tenants, and which decisions need an owner vote.', 12, '{"objectives": ["Explain which decisions council can make and which need a vote of the owners", "Describe what a strata manager does and who they answer to", "Tell a majority vote, a 3/4 vote and a unanimous vote apart, with an example of each", "Describe the rights and duties of tenants in a strata"], "sections": [], "furtherReading": [{"id": "fr_sb2_1", "title": "Roles and responsibilities in stratas (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities", "note": "Owners, council, tenants and strata managers."}, {"id": "fr_sb2_2", "title": "The strata voting process (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/voting-process", "note": "Which decisions need which kind of vote."}]}'::jsonb),
  ('sb3', 'strata_basics', 3, 'Where the money goes', 'The operating fund, the contingency reserve fund, strata fees, special levies and the annual budget.', 12, '{"objectives": ["Explain the difference between the operating fund and the contingency reserve fund", "Describe how strata fees are shared out between owners", "Explain when a special levy is used and how it''s approved", "Describe how the annual budget is approved"], "sections": [], "furtherReading": [{"id": "fr_sb3_1", "title": "The contingency reserve fund (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/finances-and-insurance/the-contingency-reserve-fund-crf", "note": "What the reserve fund is for and how it''s funded."}, {"id": "fr_sb3_2", "title": "The strata voting process (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/voting-process", "note": "Which decisions need which kind of vote."}, {"id": "fr_sb3_3", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}]}'::jsonb),
  ('cr1', 'council_ready', 1, 'Your role on council', 'How council is elected, the standard of care, conflicts of interest and confidentiality.', 12, '{"objectives": ["Explain how council members are elected and how long they serve", "Describe the standard of care every council member must meet", "Recognise a conflict of interest and say what to do about it", "Explain what council business must stay confidential"], "sections": [], "furtherReading": [{"id": "fr_cr1_1", "title": "Strata councils (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities/strata-councils", "note": "What council does, and what it can''t do without the owners."}, {"id": "fr_cr1_2", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}]}'::jsonb),
  ('cr2', 'council_ready', 2, 'Running council meetings', 'Calling and running council meetings, making decisions, hearings, and recording what was decided.', 14, '{"objectives": ["Explain how a council meeting is called and what makes a quorum", "Run an orderly meeting that reaches clear decisions", "Respond correctly when an owner asks for a hearing", "Describe what council meeting minutes must record"], "sections": [], "furtherReading": [{"id": "fr_cr2_1", "title": "Strata meetings and voting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting", "note": "Council meetings, general meetings and voting."}, {"id": "fr_cr2_2", "title": "Strata councils (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities/strata-councils", "note": "What council does, and what it can''t do without the owners."}]}'::jsonb),
  ('cr3', 'council_ready', 3, 'General meetings and voting', 'Annual and special general meetings: notice, quorum, proxies, the budget and resolutions.', 14, '{"objectives": ["Describe the notice owners must get before a general meeting", "Explain how quorum and proxies work", "Explain how the budget and 3/4 vote resolutions are approved", "Describe what happens when owners requisition a special general meeting"], "sections": [], "furtherReading": [{"id": "fr_cr3_1", "title": "Conducting an annual or special general meeting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/conducting-a-general-meeting-agm-or-sgm", "note": "Notice, quorum, proxies and running the meeting."}, {"id": "fr_cr3_2", "title": "The strata voting process (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/voting-process", "note": "Which decisions need which kind of vote."}, {"id": "fr_cr3_3", "title": "Strata meetings and voting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting", "note": "Council meetings, general meetings and voting."}]}'::jsonb),
  ('cr4', 'council_ready', 4, 'Bylaws, rules and disputes', 'The difference between bylaws and rules, enforcing them fairly, current limits, and resolving disputes.', 14, '{"objectives": ["Explain the difference between a bylaw and a rule", "Follow the steps the Act requires before fining an owner or tenant", "Describe the current limits on rental and age restriction bylaws", "Explain when a dispute can go to the Civil Resolution Tribunal"], "sections": [], "furtherReading": [{"id": "fr_cr4_1", "title": "Enforcing bylaws and rules (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/bylaws-and-rules/enforcing-bylaws-and-rules", "note": "The steps council must follow before a fine."}, {"id": "fr_cr4_2", "title": "Amending bylaws and rules (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/bylaws-and-rules/amending-bylaws-and-rules", "note": "How owners change bylaws and how council makes rules."}, {"id": "fr_cr4_3", "title": "Solution Explorer: strata property (Clicklaw)", "url": "https://www.clicklaw.bc.ca/resources/solution-explorer-strata-property", "note": "The Civil Resolution Tribunal''s free tool for strata disputes."}]}'::jsonb),
  ('cr5', 'council_ready', 5, 'Repairs, maintenance and insurance', 'Who repairs what, planning with the depreciation report, insurance and deductibles, and emergencies.', 14, '{"objectives": ["Explain who is responsible for repairing common property, limited common property and strata lots", "Use the depreciation report to plan maintenance and repairs", "Describe the strata''s insurance and how deductibles can be charged back", "Explain what council can do in an emergency without a vote"], "sections": [], "furtherReading": [{"id": "fr_cr5_1", "title": "Depreciation reports: practical tips (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/repairs-and-maintenance/depreciation-reports/practical-tips", "note": "Getting real value from the report."}, {"id": "fr_cr5_2", "title": "Depreciation report requirements (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/repairs-and-maintenance/depreciation-reports/depreciation-report-requirements", "note": "What a depreciation report must contain."}, {"id": "fr_cr5_3", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}]}'::jsonb),
  ('cr6', 'council_ready', 6, 'Records, privacy and getting help', 'The records a strata keeps, owner requests, personal information, and working with a strata manager or self-managing.', 12, '{"objectives": ["List the records a strata must keep", "Respond to an owner''s request for records on time", "Protect owners'' and tenants'' personal information", "Decide what to delegate to a strata manager, or what a self-managed council takes on"], "sections": [], "furtherReading": [{"id": "fr_cr6_1", "title": "Information and record keeping (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/information-and-record-keeping", "note": "Which records to keep, and who can see them."}, {"id": "fr_cr6_2", "title": "Strata management services (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities/strata-property-managers/strata-management-services", "note": "What a strata manager can do for council."}, {"id": "fr_cr6_3", "title": "Strata manager licensing (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities/strata-property-managers/licensing", "note": "Why strata managers must be licensed."}]}'::jsonb),
  ('t1', 'treasurer', 1, 'Reading the financial statements', 'What the monthly statements show, and the questions a treasurer should ask about them.', 12, '{"objectives": ["Read a strata''s monthly financial statements", "Compare actual spending to the budget and explain the differences", "Spot the warning signs worth raising with council"], "sections": [], "furtherReading": [{"id": "fr_t1_1", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}, {"id": "fr_t1_2", "title": "Strata Property Regulation", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/43_2000", "note": "The detailed rules that go with the Act."}]}'::jsonb),
  ('t2', 'treasurer', 2, 'The budget and strata fees', 'Building the annual budget, setting strata fees, and presenting the budget to owners.', 12, '{"objectives": ["Build a draft annual budget from past spending and known costs", "Explain how strata fees are calculated from the budget", "Present the budget to owners for approval at the AGM"], "sections": [], "furtherReading": [{"id": "fr_t2_1", "title": "The strata voting process (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/voting-process", "note": "Which decisions need which kind of vote."}, {"id": "fr_t2_2", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}]}'::jsonb),
  ('t3', 'treasurer', 3, 'The reserve fund and depreciation report', 'Contributions to the contingency reserve fund, the depreciation report''s funding models, and special levies.', 12, '{"objectives": ["Explain the rules for contributions to the contingency reserve fund", "Use the depreciation report''s funding models to plan contributions", "Explain when and how money can be spent from the reserve fund", "Decide when a special levy is the right choice"], "sections": [], "furtherReading": [{"id": "fr_t3_1", "title": "The contingency reserve fund (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/finances-and-insurance/the-contingency-reserve-fund-crf", "note": "What the reserve fund is for and how it''s funded."}, {"id": "fr_t3_2", "title": "Depreciation report requirements (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/repairs-and-maintenance/depreciation-reports/depreciation-report-requirements", "note": "What a depreciation report must contain."}, {"id": "fr_t3_3", "title": "Depreciation reports: practical tips (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/repairs-and-maintenance/depreciation-reports/practical-tips", "note": "Getting real value from the report."}]}'::jsonb),
  ('t4', 'treasurer', 4, 'Collections, arrears and controls', 'Collecting unpaid fees, liens, and the financial controls that protect the strata''s money.', 12, '{"objectives": ["Follow the steps for collecting unpaid strata fees", "Explain when the strata can register a lien", "Put in place financial controls such as signing authority and separation of duties"], "sections": [], "furtherReading": [{"id": "fr_t4_1", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}, {"id": "fr_t4_2", "title": "Strata Property Regulation", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/43_2000", "note": "The detailed rules that go with the Act."}]}'::jsonb),
  ('s1', 'secretary', 1, 'Notices and agendas', 'Notices for council and general meetings, and building a clear agenda.', 10, '{"objectives": ["Give the right notice for council and general meetings", "Build a clear agenda that separates decisions from information", "Send notices the way the Act and bylaws allow"], "sections": [], "furtherReading": [{"id": "fr_s1_1", "title": "Conducting an annual or special general meeting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting/conducting-a-general-meeting-agm-or-sgm", "note": "Notice, quorum, proxies and running the meeting."}, {"id": "fr_s1_2", "title": "Strata meetings and voting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting", "note": "Council meetings, general meetings and voting."}]}'::jsonb),
  ('s2', 'secretary', 2, 'Writing good minutes', 'What minutes must record, what to leave out, and getting them to owners on time.', 12, '{"objectives": ["Record decisions and votes clearly in council and general meeting minutes", "Decide what to leave out of minutes, including personal information", "Distribute minutes to owners within the required time"], "sections": [], "furtherReading": [{"id": "fr_s2_1", "title": "Strata meetings and voting (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/meetings-and-voting", "note": "Council meetings, general meetings and voting."}, {"id": "fr_s2_2", "title": "Information and record keeping (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/information-and-record-keeping", "note": "Which records to keep, and who can see them."}]}'::jsonb),
  ('s3', 'secretary', 3, 'Records and owner requests', 'Keeping records for the right length of time, and answering requests for records and information certificates.', 12, '{"objectives": ["Keep each kind of record for the required time", "Answer an owner''s request for records within the deadline", "Explain what an information certificate (Form B) is and who asks for one"], "sections": [], "furtherReading": [{"id": "fr_s3_1", "title": "Information and record keeping (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/information-and-record-keeping", "note": "Which records to keep, and who can see them."}, {"id": "fr_s3_2", "title": "Strata Property Act", "url": "https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/98043_00", "note": "The law itself, with the Standard Bylaws in its Schedule."}]}'::jsonb),
  ('s4', 'secretary', 4, 'Correspondence and privacy', 'Handling owners'' letters and complaints, and sharing information without breaching privacy.', 10, '{"objectives": ["Handle owners'' correspondence and complaints in writing, consistently", "Share information with owners without disclosing personal information", "Keep the owner and tenant contact list secure"], "sections": [], "furtherReading": [{"id": "fr_s4_1", "title": "Information and record keeping (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/information-and-record-keeping", "note": "Which records to keep, and who can see them."}, {"id": "fr_s4_2", "title": "Strata councils (Province of BC)", "url": "https://www2.gov.bc.ca/gov/content/housing-tenancy/strata-housing/operating-a-strata/roles-and-responsibilities/strata-councils", "note": "What council does, and what it can''t do without the owners."}]}'::jsonb)

), inserted as (
  insert into public.training_modules (track_id, order_index, title, summary, estimated_minutes, curriculum_key)
  select t.id, s.order_index, s.title, s.summary, s.estimated_minutes, s.curriculum_key
  from seed s
  join public.training_tracks t on t.code = s.track_code
  on conflict (curriculum_key) where curriculum_key is not null do nothing
  returning id, curriculum_key
)
insert into public.training_module_drafts (module_id, content)
select i.id, s.content
from inserted i
join seed s on s.curriculum_key = i.curriculum_key
on conflict (module_id) do nothing;
